region                       = "eastus2"
data_lake_name               = "tfazuredatalake"
storage_replication          = "LRS"
service_principal_end_date   = "2030-01-01T00:00:00Z"
databricks_cluster_node_type = "Standard_DS3_v2"
databricks_cluster_version   = "6.5.x-scala2.11"